---
- name: Configure interfaces and deploy OSPF
  hosts: multicat
  connection: local
  gather_facts: no
  tasks:
    - name: Create Loopback
      with_items: "{{local_loopback}}"
      ios_interface:
        name: "{{item.name}}"
        enabled: True
        state: present
    - name: Set Loopback IPs
      with_items: "{{local_loopback}}"
      ios_l3_interface:
        name: "{{item.name}}"
        ipv4: "{{item.ip_address}}"
    - name: Set Interfaces IPs
      with_items: "{{interfaces}}"
      ios_l3_interface:
        name: "{{item.name}}"
        ipv4: "{{item.ip_address}}"
    - name: Enable interface no shutdow 
      with_items: "{{interfaces}}"
      ios_interface:
        name: "{{item.name}}"
        enabled: True
        state: present
    - name: Generate config file cfg
      template: src=ospf.j2 dest={{inventory_hostname}}.cfg
    - name: Deploy ospf
      ios_config:
        src: "{{inventory_hostname}}.cfg"
    
        
      
