---

local_loopback:
  - name: Loopback0
    ip_address: 22.22.22.22/32

interfaces:
  - name: GigabitEthernet1
    ip_address: 192.168.12.2/24
  - name: GigabitEthernet2
    ip_address: 192.168.24.2/24
  - name: GigabitEthernet3
    ip_address: 192.168.23.2/24

networks:
  - net: 192.168.23.0 
    mask: 0.0.0.255
  - net: 192.168.12.0 
    mask: 0.0.0.255
  - net: 192.168.24.0 
    mask: 0.0.0.255

interface:
  - ospf_int: GigabitEthernet1
  - ospf_int: GigabitEthernet2
  - ospf_int: GigabitEthernet3

ospf_router_id: 2.2.2.2
rp_address: 22.22.22.22
ospf_process: 1
ospf_area: 0