---
interfaces:
  - name: GigabitEthernet1
    ip_address: 192.168.12.1/24
  - name: GigabitEthernet2
    ip_address: 192.168.14.1/24
  - name: GigabitEthernet3
    ip_address: 192.168.1.254/24

networks:
  - net: 192.168.1.0 255.255.255.0
  - net: 192.168.12.0 255.255.255.0
  - net: 192.168.14.0 255.255.255.0

interface:
  - ospf_int: GigabitEthernet1
  - ospf_int: GigabitEthernet2
  - ospf_int: GigabitEthernet3

ospf_process: 1
ospf_area: 0