---
local_loopback:
  - name: Loopback0
  - ip_address: 33.33.33.33/32

interfaces:
  - name: GigabitEthernet1
    ip_address: 192.168.23.3/24
  - name: GigabitEthernet2
    ip_address: 192.168.3.254/24
  
networks:
  - net: 192.168.3.0 
    mask: 0.0.0.255
  - net: 192.168.23.0 
    mask: 0.0.0.255
  
interface:
  - ospf_int: GigabitEthernet1
  - ospf_int: GigabitEthernet2


ospf_router_id: 3.3.3.3
rp-address: 22.22.22.22
ospf_process: 1
ospf_area: 0